name: Build and test for pull request to dev

# Trigger the workflow when a Pull Rrequest is created targeting the 'dev' branch
on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the code from the pull request
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
          cd frontend
          npm install

    # Step 4: Run the React application
    - name: Run React application
      run: |
          cd frontend
          npm run build

    # Step 5: Set up Python environment (for FastAPI backend)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # # Step 6: Install dependencies for FastAPI backend
    # - name: Install backend dependencies
    #   run: |
    #       cd backend
    #       pip install -r requirements.txt

    # Step 7: Run backend FastAPI application
    - name: Run FastAPI backend
      run: |
          cd Backend
          uvicorn main:app --host 0.0.0.0 --port 8000 &

    # # Step 8: Run integration tests
    # - name: Run integration tests
    #   run: |
    #       cd frontend
    #       npm run test 

    # Step 5: Set up Python environment (for FastAPI backend)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # # Step 6: Install dependencies for FastAPI backend
    - name: Install backend dependencies
      run: |
          cd Backend
          pip install -r requirements.txt

    # # Step 7: Run backend FastAPI application
    # - name: Run FastAPI backend
    #   run: |
    #       cd Backend
    #       uvicorn app.main:app --reload 

    # # Step 8: Run integration tests
    # - name: Run integration tests
    #   run: |
    #       cd frontend
    #       npm run test 