name: Push to staging on dev push

# Trigger this workflow when there is a push to the 'dev' branch
on:
  push:
    branches:
      - dev
jobs:
  push-to-staging:
    runs-on: ubuntu-latest

    steps:
        # Step 1: Checkout the code from the 'dev' branch
        - name: Checkout code
          uses: actions/checkout@v2
  
        # Step 2: Fetch all remote branches
        - name: Fetch all remote branches
          run: git fetch --all
  
        # Step 3: Checkout the 'staging' branch
        - name: Checkout staging branch
          run: git checkout staging
  
        # Step 4: Merge changes from 'dev' to 'staging'
        - name: Merge dev into staging
          run: git merge dev --allow-unrelated-histories
  
        # Step 5: Push changes to the 'staging' branch
        - name: Push to staging branch
          run: git push origin staging