name: Build, test, and push to main

on:
    push:
      branches:
        - staging
jobs:
    build-test-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

            # Step 2: Set up Docker
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

          # Step 2: Set up Node.js for React frontend
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'

        # Step 3: Install frontend dependencies
        - name: Install frontend dependencies
          run: |
              cd frontend
              npm install

        # Step 4: Build the React frontend
        - name: Build React frontend
          run: |
              cd frontend
              npm run build

        # Step 5: Set up Python for FastAPI backend
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'

        # Step 6: Install backend dependencies
        - name: Install backend dependencies
          run: |
              cd backend
              pip install -r Backend/requirements.txt

        # Step 7: Run backend FastAPI server (optional for testing integration)
        - name: Run FastAPI backend
          run: |
              cd Backend
              uvicorn app.main:app --reload 

        # Step 8: Run all tests (frontend and backend)
        - name: Run all tests
          run: |
              cd frontend
              npm run test 

        # Step 9: Set up Git
        - name: Set up Git for main push
          run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"

        # Step 10: Checkout production branch
        - name: Checkout main branch
          run: |
            git fetch origin main
            git checkout main
        
        # Step 11: Merge staging into production
        - name: Merge staging into main
          run: |
            git merge origin/staging --allow-unrelated-histories --no-ff --no-edit
        
        # Step 12: Push to production branch
        - name: Push to main branch
          run: |
            git push origin main