name: Build, test, and push to main

on:
    push:
      branches:
        - staging
jobs:
    build-test-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

            # Step 2: Set up Docker
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        