name: push to staging on dev push

# Trigger this workflow when there is a push to the 'dev' branch
on:
  push:
    branches:
      - dev

jobs:
  push-to-staging:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from the 'dev' branch
    - name: Checkout code
      uses: actions/checkout@v2

    
    # Step 2: Push changes to the 'staging' branch
    - name: Push to staging branch
      run: |
        git checkout staging
        git merge dev  # Merge changes from dev to staging
        git push origin staging  
    
   
