name: Build, test, and deploy to main

on:
    push:
      branches:
        - staging
jobs:
    build-test-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

            # Step 2: Set up Docker
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        # Step 3: Log in to DockerHub
        - name: Log in to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}